import { defineConfig } from 'tsup';

export default defineConfig((config) => [
  {
    entry: ['src/**/*.ts'],
    splitting: true,
    sourcemap: true,
    treeshake: true,
    dts: true,
    clean: true,
    minify: config.watch ? false : 'terser',
    keepNames: true,
    bundle: true,
    removeNodeProtocol: false,
    tsconfig: 'tsconfig.json',
    target: 'node22',
    format: 'esm',
    outDir: 'dist/esm',
  },
  {
    entry: ['src/**/*.ts'],
    splitting: true,
    sourcemap: true,
    treeshake: true,
    dts: true,
    clean: true,
    minify: config.watch ? false : 'terser',
    keepNames: true,
    bundle: true,
    removeNodeProtocol: false,
    tsconfig: 'tsconfig.json',
    target: 'node22',
    format: 'cjs',
    outDir: 'dist/cjs',
  },
]);
